export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO"; 
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR"; 
export const LIMPIAR_STATE_AGREGAR_PRODUCTO = "LIMPIAR_STATE_AGREGAR_PRODUCTO";
export const AGREGAR_NOMBRE  = "AGREGAR_NOMBRE";
export const AGREGAR_DESCRIPCION  = "AGREGAR_DESCRIPCION";
export const AGREGAR_PRECIO  = "AGREGAR_PRECIO";
export const OBTENER_PRODUCTOS_INICIO = "OBTENER_PRODUCTOS_INICIO"
export const OBTENER_PRODUCTOS_EXITO="OBTENER_PRODUCTOS_EXITO"
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR"
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO_INICIO"
export const ELIMINAR_PRODUCTO_EXITO = "ELIMINAR_PRODUCTO_EXITO"
export const ELIMINAR_PRODUCTO_ERROR = "ELIMINAR_PRODUCTO_ERROR"
export const ELIMINAR_PRODUCTO_CANCELAR = "ELIMINAR_PRODUCTO_CANCELAR"
export const EDITAR_PRODUCTO  = "EDITAR_PRODUCTO"
export const EDITAR_PRODUCTO_INICIO  = "EDITAR_PRODUCTO_INICIO"
export const EDITAR_PRODUCTO_ERROR =  "EDITAR_PRODUCTO_ERROR"
export const EDITAR_PRODUCTO_EXITO = "EDITAR_PRODUCTO_EXITO"
export const EDITAR_PRODUCTO_CLEAN = "EDITAR_PRODUCTO_CLEAN"


